### ISSUE TITLE
Drug Index Page uses API

### ISSUE THREAD

**Issue by ainemckay** [MHRA/products#403]
### User want
As a 3rd party user I would like to able to access drug index information through an API, so that I don't have to scrape the website and have easy access to the information.

Customer acceptance criteria

 A third party user can access the documents API. It should be self-documenting to a user who is familiar with GraphQL.

 Product page of the site can load a complete list of documents for a given product, as is the current behaviour.

Technical acceptance criteria

The public-facing web site can make use of the documents API to retrieve a list of documents which are relevant to a product. This is enabled with a query string flag and a hosts file entry.

The public-facing web site makes use of the substances API to filter those lists.
The function of the web site should be otherwise unchanged.

 The API and doc index updater should share an implementation of the rust Azure search client.

 The Cypress tests are modified to reflect the use of the API.

**Size**
M

**Value**

**Effort**

### Exit Criteria met 
- [ ] Backlog
- [ ] Discovery
- [ ] DUXD
- [ ] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by majikandy** [comment]
# QA - on non prod
When using  &useGraphQl=true it isn't returning the same results as without

To reproduce...  
Click on Z
see that 4 results are there with 12 docs in total
```
Z

ZIDOVUDINE (2 files)
ZOLEDRONIC ACID (2 files)
ZOLMITRIPTAN (2 files)
ZONISAMIDE (6 files)
```
now add &useGraphQl=true to the url
see that 3 results are there with only 8 docs in total
```
Z

ZOLEDRONIC ACID (2 files)
ZOLMITRIPTAN (2 files)
ZONISAMIDE (6 files)
```
cc @sgrowe

**Comment by sgrowe** [comment]
@majikandy 

Good find 👍  

Fixed that in #729 and ready for QA again

**Comment by majikandy** [comment]
QA 
This is now behaving correctly.

There is still an issue where documents aren't found on click through where the drug index page shows products with commas as only the text up to the comma. Described in #738 

It is ok for this card to go forward, but the caveat is that we shouldn't deploy to prod unless either #738 is fixed for non GraphQL query or GraphQL is made the default api to use.
